services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost/api
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=taskbeam
      - DB_USER=taskbeam
      - DB_PASSWORD=taskbeam_dev
      - COGNITO_USER_POOL_ID=us-east-1_S8ZsLoG1O
      - COGNITO_CONTRACTOR_CLIENT_ID=4n0rkllpa222nt25o57ku0udt4
      - COGNITO_CLIENT_CLIENT_ID=6n94nte1lq54e36hshuf0c1aec
      - AWS_REGION=us-east-1
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: taskbeam
      POSTGRES_USER: taskbeam
      POSTGRES_PASSWORD: taskbeam_dev
    ports:
      - "5432:5432"
    volumes:
      - taskbeam_db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  taskbeam_db_data:
  server_node_modules:
  client_node_modules: